spring:
  dubbo:
    application:
      # dubbo 服务名
      name: @application.name@
    # 注册中心地址（N/A表示为不启用）
    registry:
      address: @registry.address@
    # rpc 协议实现使用 dubbo 协议
    protocol:
      name: @protocol.name@
    # 服务暴露端口
    protocol:
      port: @protocol.port@
    # 基础包扫描
    base-package: @scan.basepackage@